-- MySQL Script generated by MySQL Workbench
-- Thu Dec  7 18:25:19 2017
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema quiz_depot
-- -----------------------------------------------------
DROP SCHEMA IF EXISTS `quiz_depot` ;

-- -----------------------------------------------------
-- Schema quiz_depot
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `quiz_depot` DEFAULT CHARACTER SET utf8 ;
USE `quiz_depot` ;

-- -----------------------------------------------------
-- Table `quiz_depot`.`categories`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `quiz_depot`.`categories` ;

CREATE TABLE IF NOT EXISTS `quiz_depot`.`categories` (
  `category_id` INT NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(45) NOT NULL,
  `description` VARCHAR(45) NOT NULL,
  `image` VARCHAR(256) NULL COMMENT 'nazwa obrazu z rozszerzeniem w folderze public/img/quiz/category',
  PRIMARY KEY (`category_id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `quiz_depot`.`tags`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `quiz_depot`.`tags` ;

CREATE TABLE IF NOT EXISTS `quiz_depot`.`tags` (
  `tag_id` INT NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(32) NOT NULL,
  `category_id` INT NOT NULL,
  PRIMARY KEY (`tag_id`),
  INDEX `fk_categories_idx` (`category_id` ASC),
  CONSTRAINT `fk_categories`
    FOREIGN KEY (`category_id`)
    REFERENCES `quiz_depot`.`categories` (`category_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `quiz_depot`.`quizzes`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `quiz_depot`.`quizzes` ;

CREATE TABLE IF NOT EXISTS `quiz_depot`.`quizzes` (
  `quiz_id` INT NOT NULL AUTO_INCREMENT,
  `category_id` INT NOT NULL,
  `name` VARCHAR(32) NOT NULL,
  `created` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `attemps` INT UNSIGNED NOT NULL DEFAULT 0 COMMENT 'liczba prób rozwiązywania quizu',
  `questions` INT UNSIGNED NOT NULL DEFAULT 40 COMMENT 'liczba losowanych pytań',
  `threshold` INT UNSIGNED NOT NULL DEFAULT 0 COMMENT 'Minimalna liczba pytań do przejścia quizu. Wartość 0 oznacza brak progu.',
  `time` INT UNSIGNED NOT NULL DEFAULT 0 COMMENC 'Czas trzebny na rozwiązanie quizu (w sekundach)',
  PRIMARY KEY (`quiz_id`),
  INDEX `fk_category_idx` (`category_id` ASC),
  CONSTRAINT `fk_category`
    FOREIGN KEY (`category_id`)
    REFERENCES `quiz_depot`.`categories` (`category_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `quiz_depot`.`questions`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `quiz_depot`.`questions` ;

CREATE TABLE IF NOT EXISTS `quiz_depot`.`questions` (
  `question_id` INT NOT NULL AUTO_INCREMENT,
  `quiz_id` INT NOT NULL,
  `question` VARCHAR(128) NOT NULL,
  `image` VARCHAR(256) NULL DEFAULT NULL COMMENT 'opcjonalna nazwa zdjęcia z rozszerzeniem w folderze public/img/quiz/question',
  `right_answer` VARCHAR(128) NOT NULL,
  `wrong_answer_1` VARCHAR(128) NOT NULL,
  `wrong_answer_2` VARCHAR(128) NOT NULL,
  `wrong_answer_3` VARCHAR(128) NOT NULL,
  `tags` VARCHAR(256) NULL DEFAULT NULL COMMENT 'identyfikatory tagów oddzielone średnikiem',
  PRIMARY KEY (`question_id`),
  INDEX `fk_quizzes_idx` (`quiz_id` ASC),
  CONSTRAINT ``
    FOREIGN KEY ()
    REFERENCES `quiz_depot`.`categories` ()
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_quizzes`
    FOREIGN KEY (`quiz_id`)
    REFERENCES `quiz_depot`.`quizzes` (`quiz_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
